name: FIE463
channels:
  - defaults
dependencies:
  - python=3.12.9
  - numpy=2.1.3
  - scipy=1.14.1
  - matplotlib=3.9.2
  - pandas=2.2.3
  - openpyxl=3.1.5
  - notebook=7.3.2
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_server=2.14.1
  - scikit-learn=1.6.1
  - pip
  - pip:
    - yfinance